# Don't print a new line at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = true
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[aws]
format = 'on [$symbol$profile(\($region\))]($style) '
style = "bold blue"
symbol = "🅰 "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"